### ISSUE TITLE
New php interface not placing interface name in code

### ISSUE THREAD

**Issue by still-dreaming-1** [i74ifa/vscode-create-files#2]
When using the new php interface option with the default interface template, I end up with this in the file:

```
<?php

declare(strict_types=1);
namespace Some\Namespace;
interface {{className}}
{
	
}


```
Note that the text `{{className}}` is literally in the code instead of the entered interface name. I have strict types and final enabled in the settings.

**Comment by i74ifa** [comment]
I apologize if this mistake has delayed your work. The issue was that if you had done finalClass, it wouldn't fulfill the other conditions. It was my mistake because I haven't written the tests yet. I will work on that.

[look here ](https://github.com/i74ifa/vscode-create-files/commit/14cc4be8e5b80a3f8b6cb42e38d1e08d5053c422l)

**Comment by still-dreaming-1** [comment]
It works now. Thanks!
